import type { SearchableContent } from '@/lib/definitions';

export const searchableContent: SearchableContent[] = [
  { title: 'Inicio', path: '/', description: 'Página principal de YiChess. Comienza tu viaje en el ajedrez.', keywords: 'home principal' },
  { title: 'Jugar', path: '/jugar', description: 'Juega partidas de ajedrez local con reglas oficiales. Practica tus movimientos.', keywords: 'partida local tablero fide' },
  { title: 'Reglas', path: '/reglas', description: 'Aprende las reglas básicas del ajedrez, el movimiento de las piezas y conceptos fundamentales.', keywords: 'normas piezas movimiento' },
  { title: 'Estrategias', path: '/estrategias', description: 'Descubre estrategias, aperturas y tácticas para mejorar tu juego y ganar más partidas.', keywords: 'tácticas aperturas mates' },
  { title: 'Contacto', path: '/contacto', description: 'Envíanos tus sugerencias, preguntas o comentarios sobre YiChess.', keywords: 'email mensaje' },
  { title: 'Mapa del Sitio', path: '/mapa-del-sitio', description: 'Encuentra todas las secciones y páginas de YiChess en un solo lugar.', keywords: 'sitemap estructura' },
  { title: 'Principios de Apertura', path: '/estrategias#principios-de-apertura', description: 'Controla el centro y desarrolla tus piezas para una sólida ventaja inicial.', keywords: 'estrategia apertura desarrollo' },
  { title: 'Gambito de Dama', path: '/estrategias#gambito-de-dama', description: 'Una apertura clásica y respetada que busca el control posicional.', keywords: 'estrategia apertura' },
  { title: 'Defensa Siciliana', path: '/estrategias#defensa-siciliana', description: 'La respuesta más popular y agresiva contra 1.e4. Lucha por la iniciativa.', keywords: 'estrategia apertura defensa' },
  { title: 'Enroque', path: '/estrategias#enroque', description: 'Un movimiento esencial para proteger a tu rey y conectar tus torres.', keywords: 'estrategia movimiento especial rey torre seguridad' },
  { title: 'La Clavada (Pin)', path: '/estrategias#la-clavada-pin', description: 'Inmoviliza una pieza enemiga para restringir su movimiento y crear amenazas.', keywords: 'estrategia táctica pin' },
  { title: 'La Horquilla (Fork)', path: '/estrategias#la-horquilla-fork', description: 'Ataca dos o más piezas enemigas simultáneamente con una sola pieza.', keywords: 'estrategia táctica fork' },
  { title: 'Ataque a la Descubierta', path: '/estrategias#ataque-a-la-descubierta', description: 'Mueve una pieza para desatar un ataque oculto de una pieza poderosa.', keywords: 'estrategia táctica discovered attack' },
  { title: 'El Molino (Windmill)', path: '/estrategias#el-molino-windmill', description: 'Una rara pero devastadora táctica que combina jaques a la descubierta repetidos.', keywords: 'estrategia táctica windmill' },
  { title: 'Estrategia General', path: '/estrategias#estrategia-general', description: 'Aprende a crear planes a largo plazo, controlar el tablero y coordinar tus piezas.', keywords: 'estrategia conceptos planificación' },
  { title: 'Patrones de Jaque Mate', path: '/estrategias#patrones-de-jaque-mate', description: 'Aprende las secuencias finales para dar el golpe de gracia a tu oponente.', keywords: 'estrategia táctica fin de juego mate' },
  { title: 'Jaque Mate de Coz', path: '/estrategias#jaque-mate-de-coz', description: 'Un mate espectacular dado por un caballo cuando el rey está ahogado.', keywords: 'estrategia táctica mate ahogado caballo smothered mate' },
  { title: 'Jaque del Pasillo', path: '/estrategias#jaque-del-pasillo', description: 'Un mate común en la última fila, atrapando al rey sin escapatoria.', keywords: 'estrategia táctica mate pasillo back-rank mate' },
  { title: 'El Rey', path: '/reglas?piece=El%20Rey', description: 'La pieza más importante. Solo se mueve una casilla en cualquier dirección. Si está en jaque y no puede moverse, es jaque mate.', keywords: 'pieza rey' },
  { title: 'La Dama', path: '/reglas?piece=La%20Dama', description: 'La pieza más poderosa. Se mueve cualquier número de casillas en línea recta: horizontal, vertical o diagonalmente.', keywords: 'pieza dama reina' },
  { title: 'La Torre', path: '/reglas?piece=La%20Torre', description: 'Se mueve cualquier número de casillas horizontal o verticalmente. Es una pieza poderosa en filas y columnas abiertas.', keywords: 'pieza torre' },
  { title: 'El Alfil', path: '/reglas?piece=El%20Alfil', description: 'Se mueve cualquier número de casillas en diagonal. Cada jugador tiene un alfil que se mueve en casillas claras y otro en oscuras.', keywords: 'pieza alfil' },
  { title: 'El Caballo', path: '/reglas?piece=El%20Caballo', description: 'Se mueve en forma de "L": dos casillas en una dirección y luego una en perpendicular. Es la única pieza que puede saltar sobre otras.', keywords: 'pieza caballo' },
  { title: 'El Peón', path: '/reglas?piece=El%20Pe%C3%B3n', description: 'Avanza una casilla, pero dos en su primer movimiento. Captura en diagonal. Puede coronar y convertirse en otra pieza.', keywords: 'pieza peón' },
];
